# 1. Database Connection Settings
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/homefix_db}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:Prudhvi@2003}

# 2. JPA / Hibernate Settings
# 'update' means Hibernate will automatically create or update your tables based on your Java classes
# This is important for some cloud providers
spring.jpa.hibernate.ddl-auto=update

# Default to localhost for development, but we will override this in the cloud
# 3. CORS - Allows your local React now, but we will change this on Render later
app.frontend.url=${FRONTEND_URL:http://localhost:5173} 

# This shows the actual SQL queries in your console (Great for learning!)
spring.jpa.show-sql=true

# Formats the SQL to be readable
spring.jpa.properties.hibernate.format_sql=true

# Use the MySQL dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Show only relevant info for Spring, but detailed info for our own code
logging.level.root=INFO
logging.level.com.example.fullstack.HomeFixApplication=DEBUG


#Cloudinary setup
homefix.cloudinary.name=w3tavmfm
homefix.cloudinary.key=988266469242619
homefix.cloudinary.secret=FbDVFli0VrDTp0Fr-hSCEuHx4Hw